language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: prueba-grupo4
  api_key:
    secure: v5yMlLssDeAmxCwFIv2iCFpoUv+nJOZiYlU/KRk+s+dVBUOZGsn5it6VaAMtitikQ1+g+zC3gwqNFKHRQpr/1MwlAdQUIqX+QpdE87siIZBm0dT9Cv8J82Q6uL45mekweysoCTh7OQGx/iyGCe2z2dr0lGbpmX7tAMbSn1tBn8CJnUQeaGMmM3fi3FQGJyLlU8TH64B1EK3TnDKE9oatylCCm5bWQXCq3tsFWOCen5VoYIP3qhufpfDRti8VlyVJBEDUju0kXv5lBmZpZIxOMJ8yn1YjXJtpuljBusRbh3WnqJxC6OpbEgBfyTMh+ym/+yqlBy4hyJ1Q1WB+DlrcpM0n3BvtRsaNr9m17uG3lWXkzOuJKYvOe1qQlmZ81cxlp/V8mOBSIiJRjHDZ8VBpRp55hKTwSVd2zyVCuNEx6Nz9oDg7OUZIu0E3STZhWHPWeNgfbilkYlfhOp+WWyw62CR28mWWjOAnZYMIV1nLG185Wdf4ReH8I/tWl8DjBUnuoPhcItKji0eWDq1x3ebmra0QBnojzm6ujF6pcSI9LHFPuZpj5xRFFnRbN/X/TAJ1rO/nX8qKEfLgS/GdYkN7VRYee7EJwUN/RXtqkGC2QVxYCChGFw+Ul6XUyY32J1WpZoNfuewtH1Md8fF624oV6x1qZGj1zefCJ3F/SRVb1+0=
